// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morent.API.Data;

#nullable disable

namespace Morent.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412200637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Morent.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CardHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DropoffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropoffTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Morent.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelCapacity")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            FuelCapacity = 90,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "Koenigsegg",
                            PricePerDay = 99m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 440,
                            Transmission = "Manual",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            FuelCapacity = 80,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = true,
                            Name = "Nissan GT-R",
                            PricePerDay = 80m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 440,
                            Transmission = "Manual",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            FuelCapacity = 70,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1563720223185-11003d516935?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "Rolls-Royce",
                            PricePerDay = 96m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 440,
                            Transmission = "Manual",
                            Type = "Sport"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 6,
                            FuelCapacity = 70,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "All New Rush",
                            PricePerDay = 72m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 300,
                            Transmission = "Manual",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 6,
                            FuelCapacity = 80,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "CR-V",
                            PricePerDay = 80m,
                            Rating = 4.5,
                            ReviewCount = 200,
                            Transmission = "Manual",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 6,
                            FuelCapacity = 90,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "All New Terios",
                            PricePerDay = 74m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 150,
                            Transmission = "Manual",
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 4,
                            FuelCapacity = 80,
                            FuelType = "Electric",
                            ImageUrl = "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "MG ZX Excite",
                            PricePerDay = 76m,
                            Rating = 4.2999999999999998,
                            ReviewCount = 100,
                            Transmission = "Manual",
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6,
                            FuelCapacity = 80,
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&auto=format&fit=crop",
                            IsAvailable = true,
                            IsFavorite = false,
                            Name = "New MG ZS",
                            PricePerDay = 80m,
                            Rating = 4.5,
                            ReviewCount = 180,
                            Transmission = "Manual",
                            Type = "SUV"
                        });
                });

            modelBuilder.Entity("Morent.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 2,
                            Comment = "We are very happy with the service from the MORENT App. Morent has a low price and also a large variety of cars with good and comfortable facilities.",
                            CreatedAt = new DateTime(2022, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            ReviewerAvatar = "",
                            ReviewerName = "Alex Stanton",
                            ReviewerTitle = "CEO at Bukalapak"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Comment = "We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities.",
                            CreatedAt = new DateTime(2022, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            ReviewerAvatar = "",
                            ReviewerName = "Skylar Dias",
                            ReviewerTitle = "CEO at Amazon"
                        });
                });

            modelBuilder.Entity("Morent.API.Models.Booking", b =>
                {
                    b.HasOne("Morent.API.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Morent.API.Models.Review", b =>
                {
                    b.HasOne("Morent.API.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Morent.API.Models.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
